### ISSUE TITLE
How do the databases synchronize within themselves - Adhithyan Sridhar's Architecture?

### ISSUE THREAD

**Issue by shahamit** [TechPrimers/whats-your-architecture#6]
Referring to your youtube video on this same content I would like to first of all appreciate your efforts in organizing architecture kata's. I have a question about Adhithyan Sridhar Architecture

1. How does the CouchDB database synchronize its data with Oracle and Postgress? 
2. What's the reason for having different data stores - I understand the reason for having CouchDB is to reduce the load on the source data store by providing read-only data but what's the need to have Postgress and Oracle both?

Thanks.

**Comment by MovingToWeb** [comment]
Thank you @shahamit for taking time in reviewing and understanding the Architecture.

For 
#1, There is no straight forward way to sync data between Relational DBs with CouchDB. I would prefer having another batch end of day batch which does that sync once all files are loaded into the relational DBs.

#2, Great question. Perhaps, i presume this is for a trade-off between Oracle vs Postgres depending on the costs and scaling factor. Most enterprises prefer to choose Oracle (since they already have licences and support models with Oracle). Since this is a new startup which we are going to design, I would prefer PostgreSQL. 
Also based on [this quora question](https://www.quora.com/What-is-the-technology-stack-of-Swiggy), Swiggy uses a mix of PostgresSQL and MySQL.

**Comment by shahamit** [comment]
Appreciate your quick follow up with your thoughts. 
#1 As you rightly said, synchronizing data between multiple stores is a challenge and there are trade offs that we need to aware off. In this case it would be stale data given that the sync is executed in a batch fashion only at certain times of the day.
#2 Ok, I understand now - the architecture diagram meant it would either be Oracle (if the cost is acceptable) OR Postgres otherwise. 

About Swiggy tech stack, though the quora answer does not detail on what data resides in Postgres & in MySQL, I wonder why would some one have same type of data stores (in this case relational) in an architecture. I am aware that there are important [differences ](https://developer.okta.com/blog/2019/07/19/mysql-vs-postgres#:~:text=Postgres%20is%20an%20object%2Drelational,more%20closely%20to%20SQL%20standards.)between the two but at the end both being relational stores I assume the reason of having both could be because the architecture evolved over time.

P.S - I hope you don't mind such technical discussions

**Comment by MovingToWeb** [comment]
Yes. I would love to discuss about architectures, trade offs and different perspectives. It creates a healthy discussion.

Yes, as you rightly mentioned, architectures evolve and going through a transition once a company/product grows is immense. There will be multiple products and impacts which slows down the strategy shifts. 
One other reason could be - minimal to zero benefits in moving out from mysql to postgres for some specific usecases/products.
